name: Good practices in CI/CD

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install dependencies
        run: npm install
      - name: Build application
        run: npm run build

  tests:
    runs-on: ubuntu-22.04
    needs: build
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: npm test
  
  deploy:
    runs-on: ubuntu-22.04
    needs: test
    timeout-minutes: 30
    environment: production 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy application
        env:  
          DEPLOY_PATH: /usr/share/nginx/html
        run: |
          echo "Deploying to $DEPLOY_PATH"
          ./deploy.sh
